apiVersion: v1

kind: Service

metadata:
  name: coordinates-api-svc

spec:
  type: nodePort
  selector:
    app: postgres-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080